# Generated by Django 4.2 on 2024-06-03 17:22

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_friendrequest_delete'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_email_ci_uniqueness',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='Case Insensitive Email Unique Constraint'),
        ),
    ]
